### ISSUE TITLE
Promotion doesn't load

### ISSUE THREAD

**Issue by MaxBlesch** [OpenSourceEconomics/ose-meetup#1]

**Comment by peisenha** [comment]
@SeBecker @MaxBlesch , is still relevant or can we close this?

**Comment by MaxBlesch** [comment]
For me it still doesn't load.It seams to be a random issue for some notebooks https://github.com/jupyter/notebook/issues/3035. It works perfectly on nbviewer https://nbviewer.jupyter.org/github/OpenSourceEconomics/hackathon/blob/master/promotion/OSE_promotion.ipynb. As it is only text, we could also move to a latex document and also add the pdf. If its just an issue for me and nobody else experiences it or we don't care if its visible, then we just leave it.

**Comment by peisenha** [comment]
@SeBecker , what is going on here? Why is this taking so long?

**Comment by SeBecker** [comment]
Since the notebook loads in my browser and on nbviewer (which is the main purpose of the notebook), I don't see anything what I should do here.

**Comment by peisenha** [comment]
Then please closr
